version: "2.0"
# volumes:
# data:
services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "gonodemodulo2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dev123"
